service: dongwoo-sky-api

plugins:
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2 # 서울 리전
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_ENV: ${self:provider.stage}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

custom:
  optimize:
    external: ['swagger-ui-express']

package:
  individually: true
  excludeDevDependencies: true
  include:
    - dist/**
  exclude:
    - node_modules/**
    - test/**
    - src/**
    - '*.yml'
    - '*.json'
