service: dongwoo-sky-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2 # 서울 리전
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_ENV: ${self:provider.stage}
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
    AWS_CLOUDFRONT_DOMAIN: ${env:AWS_CLOUDFRONT_DOMAIN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 'arn:aws:s3:::${env:AWS_S3_BUCKET_NAME}/*'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 'arn:aws:s3:::${env:AWS_S3_BUCKET_NAME}'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - '!test/**'
    - '!src/**'
    - '!*.yml'
    - '!*.md'
    - '!coverage/**'
    - '!.git/**'
    - '!.vscode/**'
    - 'dist/**'
    - 'package.json'
